In [113]:
import pandas as pd
UB = pd.read_csv('tailard_UB.csv')
UB = pd.DataFrame(UB)

In [114]:
from urllib.request import Request, urlopen
import urllib.parse
from bs4 import BeautifulSoup
import numpy as np
import requests

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"}

In [115]:
opt_list = dict()
dur_list = dict()
mch_list = dict() 

In [116]:
index = list(range(0, 80))
index.remove(61)

In [117]:
for i in index:
    size_text = UB.iloc[i, 1]
    size_list = size_text.rsplit('x', 1)
    n_jobs = int(size_list[0])
    n_mchs = int(size_list[1])

    UB_temp = UB.iloc[i, 2]

    i_2d = str(i+1).zfill(2)
    url = 'https://optimizizer.com/solution.php?name=ta' + str(i_2d) + '&UB=' + str(UB_temp) + '&problemclass=ta' 

    response = requests.get(url, headers=headers)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    nums = soup.get_text().rsplit(':', 1)[-1].rsplit(' back', 1)[0]
    table = list(map(int, nums.split(' ')))

    table_opt = np.array(table).reshape(n_jobs, n_mchs)
    opt_list[i+1] = table_opt

    # target_url = 'http://mistic.heig-vd.ch/taillard/problemes.dir/ordonnancement.dir/jobshop.dir/tai15_15.txt'
    # response = requests.get(target_url)
    # data = response.text
    # soup2 = BeautifulSoup(data, 'html.parser')

    # numbs = soup2.get_text().rsplit('Times')[3].rsplit('Machines')[2]
    # print(numbs)

    # # numbs = soup2.get_text().rsplit('Times')[1].rsplit('Machines')[0]
    # # new_mch = numbs.replace('\r\n', '')[1:]
    
    # # table2 = list(map(int, new_mch.split()))

    # # table_dur = np.array(table2).reshape(n_jobs, n_mchs)
    # # print(table_dur)

The ith row of each solution file represents the processing order of jobs on the ith machine
(indexing of jobs starts from zero)

In [163]:
# n_pair = [(15, 15), (20, 15), (20, 20), (30, 15), (30, 20), (50, 15), (50, 20), (100, 20)]
n_pair = [(50, 20)]
index = 61

for (n_job, n_mch) in n_pair:
    for iter in range(10):
        with open('tai_' + str(n_job) + '_' + str(n_mch) + '.txt') as f:
            contents = f.read()
        lis = contents.rsplit('=')[iter*2].replace('\n', '').split()
        res = [eval(i) for i in lis]
        table2 = np.array(res).reshape(n_job, n_mch)
        dur_list[index] = table2

        with open('tai_' + str(n_job) + '_' + str(n_mch) + '.txt') as f:
            contents = f.read()
        lis2 = contents.rsplit('=')[iter*2+1].replace('\n', '').split()
        res2 = [eval(i) for i in lis2]
        table3 = np.array(res2).reshape(n_job, n_mch)
        mch_list[index] = table3

        print(index)
        index = index + 1


61
62
63
64
65
66
67
68
69
70


In [119]:
len(dur_list)

10

In [120]:
len(mch_list)

10

In [165]:
mch_list[61]

array([[ 9, 20, 18, 16,  2,  3, 11,  8, 14, 19,  6,  7,  4,  5, 15, 12,
        17,  1, 10, 13],
       [13, 12,  4, 17,  2,  3, 10,  9, 19,  5,  1, 20, 18, 16,  6, 11,
        14, 15,  7,  8],
       [ 9,  7, 16, 15,  4,  8, 20, 19,  2, 12,  5, 13, 18, 14,  1,  3,
        10, 11, 17,  6],
       [13, 10,  6, 17,  1,  3, 14, 19,  7, 12,  2, 20,  9, 15,  8,  5,
        16, 11,  4, 18],
       [ 2,  4, 14,  5, 19,  6,  7, 10,  8,  9, 16,  1, 15, 11, 13, 20,
        17, 18,  3, 12],
       [17,  4,  5, 15,  2,  3, 11, 10,  6,  1, 19, 20,  9, 18, 13, 16,
        14,  7,  8, 12],
       [20,  5, 16,  1, 13, 14,  2,  8, 19,  6, 10,  4, 17,  9, 12,  3,
         7, 15, 11, 18],
       [10, 11,  9,  5, 15,  6, 16,  8, 19,  7, 14, 20, 18,  3, 17, 12,
         1, 13,  4,  2],
       [10, 14, 16,  8, 19,  3, 12, 20,  2,  9,  1,  5,  4, 13,  7, 17,
        15, 18, 11,  6],
       [ 7, 12, 18,  9, 17,  8,  1, 15,  5, 16,  3, 14, 19,  2, 10, 20,
        11,  6,  4, 13],
       [14,  5,  8,  7, 16, 12

In [167]:
opt_list[61]

array([[12, 39, 45, 37, 26, 44, 31, 11,  9,  6, 47, 48,  3, 34, 38, 13,
        24, 20, 42, 28],
       [ 8, 18, 27,  4, 14, 25, 33, 15, 29, 40, 23,  5, 22, 30, 16, 35,
         1, 49, 43, 32],
       [ 2, 19, 41, 46, 10,  7,  0, 17, 36, 21,  4, 14, 44, 15, 39, 38,
        36, 25, 34,  5],
       [26, 12, 20,  6, 18, 48,  0,  8, 17, 24,  1, 31,  3,  9, 11, 43,
        22,  2, 49, 13],
       [40, 23, 37, 10, 35, 28, 30, 27, 29, 46, 47, 21, 45, 32, 16, 33,
        19, 42,  7, 41],
       [43, 40, 37, 44, 20, 12, 46, 38, 24, 33, 14, 29,  8,  5, 15, 25,
        31,  3, 30,  0],
       [47, 41,  9, 19, 21,  1, 45, 13, 28, 34, 32, 22, 39, 16, 35,  7,
        49, 11, 26,  6],
       [42, 18,  2, 36, 23,  4, 17, 27, 48, 10, 16,  4,  5, 11,  1, 42,
        45, 48,  2, 23],
       [35, 31, 33, 41, 21, 36, 19, 12, 37, 10, 39, 34, 27,  6,  8, 18,
        24, 17, 29, 20],
       [25, 30, 14, 28, 43, 47, 32, 46,  0, 13, 15, 22,  9, 26, 44, 38,
         3, 49,  7, 40],
       [18, 24,  4, 42, 31,  5

In [158]:
import itertools as it

edge_list = []
for mch_idx in range(15):
    seq_temp = []
    for seq_idx in range(15):
        i = opt_list[1][seq_idx, mch_idx] #7
        j = list(mch_list[1][i]).index(mch_idx+1) #2
        seq_temp.append((i)*15 + j)
    for (i, j) in list(it.pairwise(seq_temp)):
        edge_list.append([i, j])

for num in range(0, 15*15):
    if (num+1) % 15 != 0:
        edge_list.append([num, num+1])
edge_list
             

[[107, 167],
 [167, 140],
 [140, 153],
 [153, 124],
 [124, 50],
 [50, 187],
 [187, 38],
 [38, 219],
 [219, 86],
 [86, 25],
 [25, 102],
 [102, 73],
 [73, 13],
 [13, 209],
 [30, 125],
 [125, 112],
 [112, 215],
 [215, 96],
 [96, 202],
 [202, 145],
 [145, 176],
 [176, 70],
 [70, 84],
 [84, 190],
 [190, 58],
 [58, 161],
 [161, 28],
 [28, 14],
 [165, 138],
 [138, 46],
 [46, 5],
 [5, 66],
 [66, 183],
 [183, 126],
 [126, 113],
 [113, 83],
 [83, 39],
 [39, 100],
 [100, 222],
 [222, 208],
 [208, 164],
 [164, 29],
 [91, 76],
 [76, 4],
 [4, 142],
 [142, 184],
 [184, 116],
 [116, 177],
 [177, 160],
 [160, 221],
 [221, 26],
 [26, 207],
 [207, 43],
 [43, 59],
 [59, 74],
 [74, 134],
 [150, 197],
 [197, 2],
 [2, 64],
 [64, 15],
 [15, 80],
 [80, 214],
 [214, 52],
 [52, 115],
 [115, 98],
 [98, 189],
 [189, 129],
 [129, 42],
 [42, 148],
 [148, 179],
 [75, 106],
 [106, 45],
 [45, 180],
 [180, 199],
 [199, 154],
 [154, 16],
 [16, 172],
 [172, 127],
 [127, 69],
 [69, 37],
 [37, 99],
 [99, 12],
 [12, 149],
 [

In [169]:
import itertools as it

edge_list = []
for mch_idx in range(20):
    seq_temp = []
    for seq_idx in range(50):
        i = opt_list[61][seq_idx, mch_idx] #7
        j = list(mch_list[61][i]).index(mch_idx+1) #2
        seq_temp.append((i)*20 + j)
    for (i, j) in list(it.pairwise(seq_temp)):
        edge_list.append([i, j])

for num in range(0, 50*20):
    if (num+1) % 20 != 0:
        edge_list.append([num, num+1])
edge_list
             

[[240, 170],
 [170, 54],
 [54, 524],
 [524, 811],
 [811, 876],
 [876, 946],
 [946, 847],
 [847, 710],
 [710, 510],
 [510, 372],
 [372, 186],
 [186, 333],
 [333, 293],
 [293, 395],
 [395, 266],
 [266, 545],
 [545, 847],
 [847, 223],
 [223, 412],
 [412, 54],
 [54, 766],
 [766, 611],
 [611, 611],
 [611, 439],
 [439, 240],
 [240, 17],
 [17, 488],
 [488, 686],
 [686, 742],
 [742, 742],
 [742, 686],
 [686, 811],
 [811, 742],
 [742, 316],
 [316, 885],
 [885, 847],
 [847, 710],
 [710, 473],
 [473, 592],
 [592, 738],
 [738, 454],
 [454, 240],
 [240, 454],
 [454, 156],
 [156, 412],
 [412, 876],
 [876, 671],
 [671, 936],
 [936, 316],
 [784, 366],
 [366, 399],
 [399, 247],
 [247, 474],
 [474, 812],
 [812, 839],
 [839, 366],
 [366, 630],
 [630, 613],
 [613, 492],
 [492, 348],
 [348, 70],
 [70, 409],
 [409, 213],
 [213, 935],
 [935, 303],
 [303, 339],
 [339, 48],
 [48, 935],
 [935, 839],
 [839, 679],
 [679, 859],
 [859, 553],
 [553, 755],
 [755, 812],
 [812, 474],
 [474, 24],
 [24, 655],
 [655, 964]

In [145]:
len(edge_list)

420

In [148]:
dur_list[1].flatten().reshape(-1, 1)

array([[94],
       [66],
       [10],
       [53],
       [26],
       [15],
       [65],
       [82],
       [10],
       [27],
       [93],
       [92],
       [96],
       [70],
       [83],
       [74],
       [31],
       [88],
       [51],
       [57],
       [78],
       [ 8],
       [ 7],
       [91],
       [79],
       [18],
       [51],
       [18],
       [99],
       [33],
       [ 4],
       [82],
       [40],
       [86],
       [50],
       [54],
       [21],
       [ 6],
       [54],
       [68],
       [82],
       [20],
       [39],
       [35],
       [68],
       [73],
       [23],
       [30],
       [30],
       [53],
       [94],
       [58],
       [93],
       [32],
       [91],
       [30],
       [56],
       [27],
       [92],
       [ 9],
       [78],
       [23],
       [21],
       [60],
       [36],
       [29],
       [95],
       [99],
       [79],
       [76],
       [93],
       [42],
       [52],
       [42],
       [96],
       [29],
       [61],

In [150]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor(edge_list, dtype = torch.long)
x = torch.tensor(dur_list[1].flatten().reshape(-1, 1), dtype = torch.float)
data = Data(x=x, edge_index = edge_index.t().contiguous())
data

Data(x=[225, 1], edge_index=[2, 420])

In [151]:
torch.save(data, 'example_graph.pt')